// <auto-generated />
using GeekShooping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShooping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20230707192225_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShooping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "T-Shirt 2",
                            Description = "Description T-Shirt 2",
                            ImageUrl = "https://raw.githubusercontent.com/leleomaster/leo-microservices-dotnet6/master/ShoppingImages/11_mars.jpg",
                            Name = "Name 2",
                            Price = 62.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "T-Shirt 3",
                            Description = "Description T-Shirt 3",
                            ImageUrl = "https://raw.githubusercontent.com/leleomaster/leo-microservices-dotnet6/master/ShoppingImages/11_mars.jpg",
                            Name = "Name 3",
                            Price = 63.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "T-Shirt 4",
                            Description = "Description T-Shirt 4",
                            ImageUrl = "https://raw.githubusercontent.com/leleomaster/leo-microservices-dotnet6/master/ShoppingImages/11_mars.jpg",
                            Name = "Name 4",
                            Price = 64.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-Shirt 5",
                            Description = "Description T-Shirt 5",
                            ImageUrl = "https://raw.githubusercontent.com/leleomaster/leo-microservices-dotnet6/master/ShoppingImages/11_mars.jpg",
                            Name = "Name 5",
                            Price = 65.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
